#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "helper/utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_in_purple "\n • System Dependencies\n\n"

../src/$(get_os)/bootstrap.sh
