#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "helper/utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

run_installer() {
    local -r script="../src/$1/install.sh"

    if [ -e $script ]; then
        if [ ! -x $script ]; then
            print_error "Installers must be executable: $script"
        else
            "$script"
        fi
    fi
}

main() {

    print_in_purple "\n • Run topic-specific installers\n"

    # Execute the OS-specific installer first
    run_installer "$(get_os)"

    # Order can be controlled here, in case some installers depend on others
    # running first
    run_installer "preferences"
    run_installer "git"
    run_installer "dropbox"
    run_installer "cuda"
    run_installer "ruby"
    run_installer "python" # depends on cuda / git
    run_installer "antibody"
    run_installer "atom"
    run_installer "aws"
    run_installer "vim"
    run_installer "vscode"

}

main
