#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "helper/utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

find_installers() {

    findCmd="find ../src -maxdepth 2 -name \"*~\" -prune -o"
    findCmd="$findCmd $(find_ignore_dirs) -name install.sh -print"
    eval "$findCmd"

}

run_installers() {

    IFS=$'\n' installers=($(find_installers))

    for i in "${installers[@]}"; do
        if [ ! -x "$i" ]; then
            print_error "Installers must be executable: $i"
        else
            "$i"
        fi
    done

}

main() {

    print_in_purple "\n • Run topic-specific installers\n"

    run_installers

}

main
