#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" \
    && . "helper/utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

helper/update/create_directories.sh
helper/update/create_symbolic_links.sh "$@"
helper/update/create_local_config_files.sh
